### ISSUE TITLE
Name Question - HTML5 Game Making Clubs or Web Game Making Clubs

### ISSUE THREAD

**Issue by mickfuzz** [mickfuzz/mozilla_html5_game_clubs#5]
Should the name of the resource be explicitly for HTML5 games? Or is the term Web Games more accessible? 

Web games could in theory incorporate Scratch, and while that is not the main focus of the content of this resource, Scratch is a great resource for prototyping games. 

Also if aiming for a wide audience or non-technical audience would HTML5 Game Making put some people off? 

I would really appreciate thoughts on this naming / branding issue.

**Comment by davegoopot** [comment]
I'm liking "Web Games" more. Why spend time explaining what HTML5 is or isn't? 

Just my 2p :)

**Comment by mickfuzz** [comment]
@davegoopot that's a good comment, it can be good to keep things simple. 

I found this from Mozilla https://developer.mozilla.org/en-US/docs/Games/Introduction

It mentions both Game for the Web and HTML5 platform. So maybe it's good to have Web Games as the headline and then HTML5 when you start going into detail. Interested to know what @flukeout and @chrisdavidmills think

**Comment by chrisdavidmills** [comment]
I'd just leave the "HTML5" part out altogether, personally. Back in the mid 2000s it was a major buzzword used to sell the modern web way of doing things and suite of elements, APIs, etc.

But these days it is seldom used. Even the latest spec is now a living standard, and has dropped the "5": https://html.spec.whatwg.org/multipage/

(although the W3C is still publishing snapshots: https://www.w3.org/TR/html/)

If someone asks about HTML5, you can explain where it fits in, but I reckon it confuses more than it helps. I've heard beginners say things like "Oh, so this API isn't part of HTML5. Does that mean it's incompatible with it?"

**Comment by flukeout** [comment]
I agree with @chrisdavidmills here. Having HTML in the title suggests that HTML is a core aspect of making these games, which in the case of Phaser for example, isn't really the case since it relies on the canvas.

**Comment by mickfuzz** [comment]
Thanks everyone that was really helpful! 

Name revision underway in time for Moz Fest.

**Comment by mickfuzz** [comment]
It's renamed now to https://github.com/mickfuzz/mozilla-webgame-clubs
